/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as BandejaRouteImport } from './routes/bandeja'
import { Route as CampanasRouteImport } from './routes/campanas'
import { Route as CarteraRouteImport } from './routes/cartera'
import { Route as FlujosRouteImport } from './routes/flujos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as UtgaRouteImport } from './routes/utga'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'
import { Route as ApiWebhooksN8nInboundRouteImport } from './routes/api/webhooks/n8n.inbound'
import { Route as ApiWebhooksN8nReplyRouteImport } from './routes/api/webhooks/n8n.reply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaRoute = BandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanasRoute = CampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteraRoute = CarteraRouteImport.update({
  id: '/cartera',
  path: '/cartera',
  getParentRoute: () => rootRouteImport,
} as any)
const FlujosRoute = FlujosRouteImport.update({
  id: '/flujos',
  path: '/flujos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const UtgaRoute = UtgaRouteImport.update({
  id: '/utga',
  path: '/utga',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksN8nInboundRoute = ApiWebhooksN8nInboundRouteImport.update({
  id: '/api/webhooks/n8n/inbound',
  path: '/api/webhooks/n8n/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksN8nReplyRoute = ApiWebhooksN8nReplyRouteImport.update({
  id: '/api/webhooks/n8n/reply',
  path: '/api/webhooks/n8n/reply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/bandeja': typeof BandejaRoute
  '/campanas': typeof CampanasRoute
  '/cartera': typeof CarteraRoute
  '/flujos': typeof FlujosRoute
  '/login': typeof LoginRoute
  '/soporte': typeof SoporteRoute
  '/utga': typeof UtgaRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/webhooks/n8n/inbound': typeof ApiWebhooksN8nInboundRoute
  '/api/webhooks/n8n/reply': typeof ApiWebhooksN8nReplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/bandeja': typeof BandejaRoute
  '/campanas': typeof CampanasRoute
  '/cartera': typeof CarteraRoute
  '/flujos': typeof FlujosRoute
  '/login': typeof LoginRoute
  '/soporte': typeof SoporteRoute
  '/utga': typeof UtgaRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/webhooks/n8n/inbound': typeof ApiWebhooksN8nInboundRoute
  '/api/webhooks/n8n/reply': typeof ApiWebhooksN8nReplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/bandeja': typeof BandejaRoute
  '/campanas': typeof CampanasRoute
  '/cartera': typeof CarteraRoute
  '/flujos': typeof FlujosRoute
  '/login': typeof LoginRoute
  '/soporte': typeof SoporteRoute
  '/utga': typeof UtgaRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/webhooks/n8n/inbound': typeof ApiWebhooksN8nInboundRoute
  '/api/webhooks/n8n/reply': typeof ApiWebhooksN8nReplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/bandeja'
    | '/campanas'
    | '/cartera'
    | '/flujos'
    | '/login'
    | '/soporte'
    | '/utga'
    | '/whatsapp'
    | '/api/webhooks/whatsapp'
    | '/api/webhooks/n8n/inbound'
    | '/api/webhooks/n8n/reply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/bandeja'
    | '/campanas'
    | '/cartera'
    | '/flujos'
    | '/login'
    | '/soporte'
    | '/utga'
    | '/whatsapp'
    | '/api/webhooks/whatsapp'
    | '/api/webhooks/n8n/inbound'
    | '/api/webhooks/n8n/reply'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/bandeja'
    | '/campanas'
    | '/cartera'
    | '/flujos'
    | '/login'
    | '/soporte'
    | '/utga'
    | '/whatsapp'
    | '/api/webhooks/whatsapp'
    | '/api/webhooks/n8n/inbound'
    | '/api/webhooks/n8n/reply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  BandejaRoute: typeof BandejaRoute
  CampanasRoute: typeof CampanasRoute
  CarteraRoute: typeof CarteraRoute
  FlujosRoute: typeof FlujosRoute
  LoginRoute: typeof LoginRoute
  SoporteRoute: typeof SoporteRoute
  UtgaRoute: typeof UtgaRoute
  WhatsappRoute: typeof WhatsappRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
  ApiWebhooksN8nInboundRoute: typeof ApiWebhooksN8nInboundRoute
  ApiWebhooksN8nReplyRoute: typeof ApiWebhooksN8nReplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja': {
      id: '/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof BandejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanas': {
      id: '/campanas'
      path: '/campanas'
      fullPath: '/campanas'
      preLoaderRoute: typeof CampanasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartera': {
      id: '/cartera'
      path: '/cartera'
      fullPath: '/cartera'
      preLoaderRoute: typeof CarteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flujos': {
      id: '/flujos'
      path: '/flujos'
      fullPath: '/flujos'
      preLoaderRoute: typeof FlujosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utga': {
      id: '/utga'
      path: '/utga'
      fullPath: '/utga'
      preLoaderRoute: typeof UtgaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/n8n/inbound': {
      id: '/api/webhooks/n8n/inbound'
      path: '/api/webhooks/n8n/inbound'
      fullPath: '/api/webhooks/n8n/inbound'
      preLoaderRoute: typeof ApiWebhooksN8nInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/n8n/reply': {
      id: '/api/webhooks/n8n/reply'
      path: '/api/webhooks/n8n/reply'
      fullPath: '/api/webhooks/n8n/reply'
      preLoaderRoute: typeof ApiWebhooksN8nReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  BandejaRoute: BandejaRoute,
  CampanasRoute: CampanasRoute,
  CarteraRoute: CarteraRoute,
  FlujosRoute: FlujosRoute,
  LoginRoute: LoginRoute,
  SoporteRoute: SoporteRoute,
  UtgaRoute: UtgaRoute,
  WhatsappRoute: WhatsappRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
  ApiWebhooksN8nInboundRoute: ApiWebhooksN8nInboundRoute,
  ApiWebhooksN8nReplyRoute: ApiWebhooksN8nReplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
