/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as BandejaRouteImport } from './routes/bandeja'
import { Route as CampanasRouteImport } from './routes/campanas'
import { Route as CarteraRouteImport } from './routes/cartera'
import { Route as ChatInternoRouteImport } from './routes/chat-interno'
import { Route as FlujosRouteImport } from './routes/flujos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as UtgaRouteImport } from './routes/utga'
import { Route as WhatsappRouteImport } from './routes/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaRoute = BandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanasRoute = CampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteraRoute = CarteraRouteImport.update({
  id: '/cartera',
  path: '/cartera',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatInternoRoute = ChatInternoRouteImport.update({
  id: '/chat-interno',
  path: '/chat-interno',
  getParentRoute: () => rootRouteImport,
} as any)
const FlujosRoute = FlujosRouteImport.update({
  id: '/flujos',
  path: '/flujos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const UtgaRoute = UtgaRouteImport.update({
  id: '/utga',
  path: '/utga',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/bandeja': typeof BandejaRoute
  '/campanas': typeof CampanasRoute
  '/cartera': typeof CarteraRoute
  '/chat-interno': typeof ChatInternoRoute
  '/flujos': typeof FlujosRoute
  '/login': typeof LoginRoute
  '/soporte': typeof SoporteRoute
  '/usuarios': typeof UsuariosRoute
  '/utga': typeof UtgaRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/bandeja': typeof BandejaRoute
  '/campanas': typeof CampanasRoute
  '/cartera': typeof CarteraRoute
  '/chat-interno': typeof ChatInternoRoute
  '/flujos': typeof FlujosRoute
  '/login': typeof LoginRoute
  '/soporte': typeof SoporteRoute
  '/usuarios': typeof UsuariosRoute
  '/utga': typeof UtgaRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/bandeja': typeof BandejaRoute
  '/campanas': typeof CampanasRoute
  '/cartera': typeof CarteraRoute
  '/chat-interno': typeof ChatInternoRoute
  '/flujos': typeof FlujosRoute
  '/login': typeof LoginRoute
  '/soporte': typeof SoporteRoute
  '/usuarios': typeof UsuariosRoute
  '/utga': typeof UtgaRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/bandeja'
    | '/campanas'
    | '/cartera'
    | '/chat-interno'
    | '/flujos'
    | '/login'
    | '/soporte'
    | '/usuarios'
    | '/utga'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/bandeja'
    | '/campanas'
    | '/cartera'
    | '/chat-interno'
    | '/flujos'
    | '/login'
    | '/soporte'
    | '/usuarios'
    | '/utga'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/bandeja'
    | '/campanas'
    | '/cartera'
    | '/chat-interno'
    | '/flujos'
    | '/login'
    | '/soporte'
    | '/usuarios'
    | '/utga'
    | '/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  BandejaRoute: typeof BandejaRoute
  CampanasRoute: typeof CampanasRoute
  CarteraRoute: typeof CarteraRoute
  ChatInternoRoute: typeof ChatInternoRoute
  FlujosRoute: typeof FlujosRoute
  LoginRoute: typeof LoginRoute
  SoporteRoute: typeof SoporteRoute
  UsuariosRoute: typeof UsuariosRoute
  UtgaRoute: typeof UtgaRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja': {
      id: '/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof BandejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanas': {
      id: '/campanas'
      path: '/campanas'
      fullPath: '/campanas'
      preLoaderRoute: typeof CampanasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartera': {
      id: '/cartera'
      path: '/cartera'
      fullPath: '/cartera'
      preLoaderRoute: typeof CarteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-interno': {
      id: '/chat-interno'
      path: '/chat-interno'
      fullPath: '/chat-interno'
      preLoaderRoute: typeof ChatInternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flujos': {
      id: '/flujos'
      path: '/flujos'
      fullPath: '/flujos'
      preLoaderRoute: typeof FlujosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utga': {
      id: '/utga'
      path: '/utga'
      fullPath: '/utga'
      preLoaderRoute: typeof UtgaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  BandejaRoute: BandejaRoute,
  CampanasRoute: CampanasRoute,
  CarteraRoute: CarteraRoute,
  ChatInternoRoute: ChatInternoRoute,
  FlujosRoute: FlujosRoute,
  LoginRoute: LoginRoute,
  SoporteRoute: SoporteRoute,
  UsuariosRoute: UsuariosRoute,
  UtgaRoute: UtgaRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
