/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsignacionesRouteImport } from './routes/asignaciones'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as BandejaRouteImport } from './routes/bandeja'
import { Route as CalidadRouteImport } from './routes/calidad'
import { Route as CampanasRouteImport } from './routes/campanas'
import { Route as ChatInternoRouteImport } from './routes/chat-interno'
import { Route as DepartamentosRouteImport } from './routes/departamentos'
import { Route as EscalacionesRouteImport } from './routes/escalaciones'
import { Route as FlujosRouteImport } from './routes/flujos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UsuariosRouteImport } from './routes/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsignacionesRoute = AsignacionesRouteImport.update({
  id: '/asignaciones',
  path: '/asignaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaRoute = BandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => rootRouteImport,
} as any)
const CalidadRoute = CalidadRouteImport.update({
  id: '/calidad',
  path: '/calidad',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanasRoute = CampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatInternoRoute = ChatInternoRouteImport.update({
  id: '/chat-interno',
  path: '/chat-interno',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartamentosRoute = DepartamentosRouteImport.update({
  id: '/departamentos',
  path: '/departamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalacionesRoute = EscalacionesRouteImport.update({
  id: '/escalaciones',
  path: '/escalaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const FlujosRoute = FlujosRouteImport.update({
  id: '/flujos',
  path: '/flujos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asignaciones': typeof AsignacionesRoute
  '/auditoria': typeof AuditoriaRoute
  '/bandeja': typeof BandejaRoute
  '/calidad': typeof CalidadRoute
  '/campanas': typeof CampanasRoute
  '/chat-interno': typeof ChatInternoRoute
  '/departamentos': typeof DepartamentosRoute
  '/escalaciones': typeof EscalacionesRoute
  '/flujos': typeof FlujosRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asignaciones': typeof AsignacionesRoute
  '/auditoria': typeof AuditoriaRoute
  '/bandeja': typeof BandejaRoute
  '/calidad': typeof CalidadRoute
  '/campanas': typeof CampanasRoute
  '/chat-interno': typeof ChatInternoRoute
  '/departamentos': typeof DepartamentosRoute
  '/escalaciones': typeof EscalacionesRoute
  '/flujos': typeof FlujosRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asignaciones': typeof AsignacionesRoute
  '/auditoria': typeof AuditoriaRoute
  '/bandeja': typeof BandejaRoute
  '/calidad': typeof CalidadRoute
  '/campanas': typeof CampanasRoute
  '/chat-interno': typeof ChatInternoRoute
  '/departamentos': typeof DepartamentosRoute
  '/escalaciones': typeof EscalacionesRoute
  '/flujos': typeof FlujosRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asignaciones'
    | '/auditoria'
    | '/bandeja'
    | '/calidad'
    | '/campanas'
    | '/chat-interno'
    | '/departamentos'
    | '/escalaciones'
    | '/flujos'
    | '/login'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asignaciones'
    | '/auditoria'
    | '/bandeja'
    | '/calidad'
    | '/campanas'
    | '/chat-interno'
    | '/departamentos'
    | '/escalaciones'
    | '/flujos'
    | '/login'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/asignaciones'
    | '/auditoria'
    | '/bandeja'
    | '/calidad'
    | '/campanas'
    | '/chat-interno'
    | '/departamentos'
    | '/escalaciones'
    | '/flujos'
    | '/login'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsignacionesRoute: typeof AsignacionesRoute
  AuditoriaRoute: typeof AuditoriaRoute
  BandejaRoute: typeof BandejaRoute
  CalidadRoute: typeof CalidadRoute
  CampanasRoute: typeof CampanasRoute
  ChatInternoRoute: typeof ChatInternoRoute
  DepartamentosRoute: typeof DepartamentosRoute
  EscalacionesRoute: typeof EscalacionesRoute
  FlujosRoute: typeof FlujosRoute
  LoginRoute: typeof LoginRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asignaciones': {
      id: '/asignaciones'
      path: '/asignaciones'
      fullPath: '/asignaciones'
      preLoaderRoute: typeof AsignacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja': {
      id: '/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof BandejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calidad': {
      id: '/calidad'
      path: '/calidad'
      fullPath: '/calidad'
      preLoaderRoute: typeof CalidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanas': {
      id: '/campanas'
      path: '/campanas'
      fullPath: '/campanas'
      preLoaderRoute: typeof CampanasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-interno': {
      id: '/chat-interno'
      path: '/chat-interno'
      fullPath: '/chat-interno'
      preLoaderRoute: typeof ChatInternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departamentos': {
      id: '/departamentos'
      path: '/departamentos'
      fullPath: '/departamentos'
      preLoaderRoute: typeof DepartamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalaciones': {
      id: '/escalaciones'
      path: '/escalaciones'
      fullPath: '/escalaciones'
      preLoaderRoute: typeof EscalacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flujos': {
      id: '/flujos'
      path: '/flujos'
      fullPath: '/flujos'
      preLoaderRoute: typeof FlujosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsignacionesRoute: AsignacionesRoute,
  AuditoriaRoute: AuditoriaRoute,
  BandejaRoute: BandejaRoute,
  CalidadRoute: CalidadRoute,
  CampanasRoute: CampanasRoute,
  ChatInternoRoute: ChatInternoRoute,
  DepartamentosRoute: DepartamentosRoute,
  EscalacionesRoute: EscalacionesRoute,
  FlujosRoute: FlujosRoute,
  LoginRoute: LoginRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
